language: rust
rust:
  stable

cache: cargo
dist: trusty
sudo: required
python:
  - "3.4"
env:
  global:
  - PROJECT_NAME=skim

matrix:
  include:
  - os: osx
    rust: nightly
    env: TARGET=x86_64-apple-darwin
  - os: linux
    rust: nightly
    env: TARGET=x86_64-unknown-linux-gnu

before_install:
  - export PATH="$PATH:$HOME/.cargo/bin"

  - sudo add-apt-repository ppa:jonathonf/python-3.6
  - sudo apt-get update
  - sudo apt-get install python3.6
  - python3.6 -V

install:
 - sudo apt-get install -y tmux zsh

script:
  - cargo build --release --verbose
  - cargo test --verbose
  - tmux new "python3.6 test/test_skim.py > out && touch ok" && cat out && [ -e ok ]

before_deploy:
  - bash ci/before_deploy.sh

deploy:
  provider: releases
  api_key:
  - secure: vmF0/waQcwHLnsurJmb+zXjL4kjdDyLgDZ6UwLY3RzAu6IUWwE3YG6n40X4kwcmGeVBr9OXooFUFYGXnv+uUsgGCuXSXxr9+SL16YOy5YKp1SAEkdIBZb0PTXOXiiGi9O5EDSRYlvkJ9qEEO0UqvQ0NO0VY/1Zhd2pDLrdkkoWuC7SKq8QCLZA3LqfXKEq1WwAwbvJzyTcqgUWSPOeYF0+gec0wTd1W9AjpNX20vzhdVU2VC9gHWhDtaA9cHyk/tGc9HQpMwozIZokdnD3+K2trXcpwMQUkv95zODeyUgcFlv3gtXPVzlhkhsWRLwhtIPUDPbGeLwizRo8T8DAaKXlim3rwdlt7NanTkp4TztlbFK+TaKZyvZdVUDAAX3NTpZLaDO9mFOk8yeswP6yMChiCUxxItkcNdbgD+uBgoAR25vSYf1/j9+vZPg65m9cA+R6cIliFzoGTtlVp+Yv5JTUJVXjSZrPyUZ1i/S6CTqJLLz+I/sFSTKawcmxHBMlCRnzr3tHbh+ikGcYCnR7ZcsjurJ3crStNrs+afUNDtmdOmUmquACQ5AygBPf7KBy/4/xmsJ2mpKSeZTSgO//tvYRkhQMfVexU4aC6N8OXqpsLM+3IcoxTMxmTtey2dP0zIYh/hOWIaOKUTjh4rqu5kx9Z8cvJl4PnYFHferh/6lwY=
  file_glob: true
  file: "${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.*"
  skip_cleanup: true
  on:
    condition: "$TRAVIS_RUST_VERSION = nightly"
    tags: true

branches:
  only:
  - master
  - "/^v\\d+\\.\\d+\\.\\d+.*$/"

notifications:
  email:
    on_success: never
