[package]
name = "skim"
version = "0.2.1-beta.1"
authors = ["Mark Wallace <lotabout@gmail.com>"]

[[bin]]
name = "sk"

[dependencies]
libc = "*"
getopts = "0.2"
regex = "0.2"
lazy_static = "0.2.1"
clippy = {version = "*", optional = true}
shlex = "0.1.1"
utf8parse = "0.1.0"

[dependencies.ncurses]
version = "*"
features = ["wide"]

[features]
default = []

[profile.release]
debug = false
