[package]
name = "skim"
version = "0.3.0"
authors = ["Mark Wallace <lotabout@gmail.com>"]
description = "Fuzzy Finder in rust!"
documentation = "https://github.com/lotabout/skim"
homepage = "https://github.com/lotabout/skim"
repository = "https://github.com/lotabout/skim"
readme  = "README.md"
keywords = ["fuzzy", "menu", "util"]
license = "MIT"

[[bin]]
name = "sk"
path = "src/main.rs"

[dependencies]
libc = "0.2.20"
regex = "0.2"
lazy_static = "0.2.8"
clippy = {version = "0.0.162", optional = true}
shlex = "0.1.1"
utf8parse = "0.1.0"
unicode-width = "0.1.4"
termion = "*"
log = "0.3.8"
env_logger = "0.4.3"
time = "*"
clap = "2.26.2"

[features]
default = []

[profile.release]
debug = false
